name: "Publish docker image"
description: "Pushes build artifacts to DockerHub"
inputs:
  registry-username:
    description: 'Username for image registry'
    required: true
  registry-access-token:
    description: 'Access token for image registry'
    required: true
  docker-registry:
    description: 'Docker registry'
    required: false
    default: 'ghcr.io'
  dockerfile-path:
    description: 'Path to dockerfile directory'
    required: false
    default: './target'

runs:
  using: composite
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ inputs.docker-registry }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-access-token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: |
          ${{ env.ECR_REGISTRY }}/${{ github.repository }}
          ${{ inputs.docker-registry }}/${{ github.repository }}
        tags: |
          type=sha

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ${{ inputs.dockerfile-path }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
